#include <doctest/doctest.h>
#include <sodium.h>

TEST_CASE("libsodium")
{
  SUBCASE("reading")
  {
    // https://doc.libsodium.org/
    // the style of document is different from others: 
    // - it shows a simple usage supposing basic understanding of encryption
    // - code to show the usage is not detailed
    // - hence it requires some to get acquainted

    // libsodium is also called NaCl. hence it means salt.

    SUBCASE("quickstart")
    {
      // https://doc.libsodium.org/quickstart

      auto rc = sodium_init();

      SUBCASE("difference between secrete key and password")
      {
        // secrete key is a stream of bits generated by algorithms
      }

      SUBCASE("checking funtion call")
      {
        // xchacha20 ? aes-gcm?
      }

      SUBCASE("encrypt memory")
      {
        // crypto_secretbox_keygen();
        // randombytes_buf();
        // crypto_secretbox_easy();
        // crypto_secretbox_open_easy();
      }

      SUBCASE("encryt file with a password")
      {
        // crypto_pwhash();
        // crypto_secretstream_*
      }

      SUBCASE("key exchange")
      {
        // crypto_kx_keypair();
        // crypto_kx_client_session_keys();
        // crypto_kx_server_session_keys();
      }
    }

    SUBCASE("helpers")
    {
      // side-channel attacks: attacks using other information outside crypto algorithms
      // like timing of memcmp.

      // sodium_memcmp()
      // sodium_bin2hex()
      // sodium_hex2bin()
      // sodium_bin2base64()
      // sodium_base642bin()
      // 
    }
  }

  SUBCASE("encryption")
  {
    // https://doc.libsodium.org/secret-key_cryptography/secretbox
    // 

  }

  SUBCASE("key exchange")
  {

  }

  SUBCASE("hashing")
  {

  }


  SUBCASE("study the other usage")
  {
    // nonce generation from initialization vector
    // key exchange
  }
}